### ISSUE TITLE
vprof does not handle scripts with arguments properly

### ISSUE THREAD

**Issue by nvdv** [nvdv/vprof#13]
```vprof``` can't handle scripts that take arguments after the script name (sys.argv). It would be super helpful if it did.

**Comment by heikoheiko** [comment]
+1

**Comment by test-account-0** [comment]
+1

**Comment by nvdv** [comment]
Looks like this one is fixed now. 
Dev version from GitHub should process scripts with arguments properly. 
I will update PyPi version ASAP.
