### ISSUE TITLE
vprof can't open default web browser on Windows

### ISSUE THREAD

**Issue by nvdv** [nvdv/vprof#14]
```vprof``` cannot open default web browser on Windows, since ```open``` is not a command on Windows.

**Comment by jorisvandenbossche** [comment]
So from my first tests, it seems to work on Windows (with python 2.7), apart from the line:

```
subprocess.call(['open', 'http://%s:%s' % (host, port)])
```

If I remove that line, it works and I see the result if I manually browse to the url. 
Using this instead also works:

```
import webbrowser
webbrowser.open('http://localhost:{0}/'.format(port))
```

But I don't know if that works as good as the subprocess open on other platforms. If you think this is OK, I can do a PR

**Comment by nvdv** [comment]
Looks like using ```webbrowser.open``` should fix this issue. PR would be much appreciated :)
