### ISSUE TITLE
'Process' object has no attribute 'memory_info'

### ISSUE THREAD

**Issue by michael-lazar** [nvdv/vprof#18]
I installed through pip on python 2.7.5 and ran into an error when trying to launch

```
  File ".../lib/python2.7/site-packages/vprof/profile_wrappers.py", line 27, in get_memory_usage
    memory_info = psutil.Process(os.getpid()).memory_info()
AttributeError: 'Process' object has no attribute 'memory_info'
```

Turned out I had a really old version of psutil installed (version 1.2.1). Running ``pip install -U psutil`` fixed the problem. I would suggest specifying a minimum version in you requirements.txt file, something like ``psutil>=3`` would probably do it.

**Comment by nvdv** [comment]
Thanks!
