### ISSUE TITLE
Support windows by converting the makefile to setup.py

### ISSUE THREAD

**Issue by bendtherules** [nvdv/vprof#20]
The project looks great, and because of the makefile it wont work on Windows. Are there any other linux-specific things?

It will be great to move that over to some cross-platform code, using python (setup.py or similar), considering that the main project is itself cross-compatible (I think),

**Comment by nvdv** [comment]
It should work on Windows (at least when #12 will be fixed), you just need to install it via  ```pip install vprof```. 
Makefile is needed to install dev version of ```vprof```. Nevertheless it is valid point. 
Thanks!

**Comment by nvdv** [comment]
```vprof``` does not use ```make``` anymore, I ported everything to ```setuptools```. 
This one should be resolved now.
