### ISSUE TITLE
Provide a way to share the results with others who don't have vprof

### ISSUE THREAD

**Issue by hschilling** [nvdv/vprof#23]
Maybe there is a way to do this. If I save off the whole Webpage, including supporting files, I get the initial graphics and text but the mouseovers don't work, I assume because there is no node.js server to provide that info?

I should have mentioned that the Flame chart is great!

**Comment by nvdv** [comment]
Thanks!
Currently there's no reliable way to save previously rendered page with all interactive elements.
But since the page is rendered on load, in theory it is possible to render it from provided JSON file.

**Comment by hschilling** [comment]
OK. Thanks! If I had the time, I would love to try to add that capability.

**Comment by soupault** [comment]
[Bokeh](http://bokeh.pydata.org/en/latest/docs/gallery.html) allows to generate the web pages with data included. Probably, is an overkill due to it's dependencies, but also could be a solution.

**Comment by nvdv** [comment]
vprof can render profiled stats from JSON now, so closing this one.
