### ISSUE TITLE
flame chart -> flame graph

### ISSUE THREAD

**Issue by brendangregg** [nvdv/vprof#36]
Looks great! Quick observation and minor note about terminology: the visualization looks like a "flame graph", where the x-axis spans the population (which can be sorted alphabetically, to maximize frame merging), whereas a "flame chart" (as Google has named them) has the passage of time on the x-axis. Both are useful for different reasons (and if the profiler retains individual timestamped samples, you have all the data you need, and could display both in separate tabs).

So I'd rename this to "flame graph", to avoid confusion. And maybe add a "flame chart" tab later on, where it does show the passage of time. Both are useful for different kinds of problems (flame graphs for aggregate big picture view, and flame charts for time series issues).

More info on flame graphs: http://queue.acm.org/detail.cfm?id=2927301

**Comment by nvdv** [comment]
Thanks for reporting and thanks for your work in performance analysis!

**Comment by barnabyrobson** [comment]
Thanks for clarifying it is a flame graph not a flame chart. However I was really hoping it was a flame chart as I'd love to see how the functions are called and what the critical path is. Is there any chance in a flame chart version that covers threads of execution ?

**Comment by nvdv** [comment]
At present `vprof` uses `cProfile` to generate stats for flame graphs and `cProfile` does not support multithreading. But  `vprof` can use something more suitable for this purpose in future.
