### ISSUE TITLE
Examples have non-existing arguments

### ISSUE THREAD

**Issue by runarfu** [nvdv/vprof#37]
I just installed `vprof` with `pip`. Then I tried one of the examples with my script:
```bash
$ vprof -c cmh -s "my_script.py"
usage: vprof [-h] [--port PORT] [--debug] [-n] options src
vprof: error: unrecognized arguments: -c -s
```
Examples should be updated, for example like this:
```bash
$ vprof cmh my_script.py
```

**Comment by nvdv** [comment]
Hi, for some reason ```pip install vprof``` installs v0.22 instead of v0.3.
Examples are correct for v0.3. I've documented this issue (https://github.com/nvdv/vprof/issues/38) and current workaround is ```pip install vprof==0.3```.
Sorry about that.

**Comment by runarfu** [comment]
Great, thanks!
