### ISSUE TITLE
-c and -s switches aren't working 

### ISSUE THREAD

**Issue by Morrolan** [nvdv/vprof#40]
In Python 3.5.1, vprof freshly installed via '**pip3.5 vprof**'.

-c and -s switches aren't working, so README is incorrect.

In order to get it working, I have to do:

**vprof cmh "myscript.py --my-option 1"**

**Comment by nvdv** [comment]
For some reason at present ```pip install vprof``` installs v0.22 instead of latest v0.3. README is for v0.3. (issue is tracked here #38)
Current workaround: pip install vprof==0.3

**Comment by nvdv** [comment]
Should be fine now, since #38 is fixed.
