### ISSUE TITLE
Add information about version of vprof into -h 

### ISSUE THREAD

**Issue by rojaster** [nvdv/vprof#41]
May be you should add information about version of vprof into help?

**Comment by nvdv** [comment]
On May 20, 2016 8:03 PM, "alekum" <notifications@github.com> wrote:
>
> May be you should add information about version of vprof into help?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
<https://github.com/nvdv/vprof/issues/41>
