### ISSUE TITLE
i run vprof. my py program starts. but where to see the charts?

### ISSUE THREAD

**Issue by saintthor** [nvdv/vprof#45]
i didn't find detail documents..

**Comment by nvdv** [comment]
Stats should appear in new tab of default web browser. If they didn't, try
to open localhost at 8000 port.

**Comment by jungle-boogie** [comment]
How can you do it remotely with this:

`vprof -c cm  -s vprof/vprof/tests/runtime_profile_test.py`

**Comment by saintthor** [comment]
there is nothing at localhost:8000.
i run the command as:
vprof --debug cm "LttServer.py"
neither -c nor -s is supported. it tells me:
usage: vprof [-h] [--port PORT] [--debug] [-n] options src

**Comment by nvdv** [comment]
#38 is fixed now and README.md has correct instructions now.
