### ISSUE TITLE
Profiling long running application

### ISSUE THREAD

**Issue by Ngo-The-Trung** [nvdv/vprof#49]
For long running applications (web server) is it possible to view intermediary results while the application is still running?

**Comment by nvdv** [comment]
Hi, unfortunately, currently it's not possible.

**Comment by TrungACZNE** [comment]
I haven't taken a look at the source yet, but do you mean it's not possible (or exceedingly difficult) to implement, or it's implementable, just not part of the current feature set?

**Comment by nvdv** [comment]
It's doable, but  `vprof` gets it's flame graph stats from `cProfile`  module and it does not seem to support returning intermediate results during profiling. Also it will certainly increase profiling overhead and require some UI adjustments.

**Comment by nvdv** [comment]
Intermediate results will require serious redesign of the package, so it's out of scope now.
