### ISSUE TITLE
Cluttered Output

### ISSUE THREAD

**Issue by shardool-freightwalla** [nvdv/vprof#51]
![screen shot 2016-06-02 at 7 34 20 pm](https://cloud.githubusercontent.com/assets/17472264/15747597/0f10462c-28f9-11e6-916d-bd8481e58f80.png)
![image](https://cloud.githubusercontent.com/assets/17472264/15747570/e8df64f6-28f8-11e6-9765-8de5ecd29539.png)

Any reason why this may be happening ?

**Comment by nvdv** [comment]
Looks like rendering issue.
It seems that stack is pretty large and most of function calls are not significant, but they take some height.

**Comment by nvdv** [comment]
It's related to #32.

**Comment by nvdv** [comment]
After mentioned commit all nodes which cumulative time is less than 0,5% of total run time won't be displayed and won't take any height.
At some point cutoff parameter will be set from UI, but it'll be tracked under #32 .
