### ISSUE TITLE
Allow code heatmap to show time taken per line as well as execution count

### ISSUE THREAD

**Issue by mdfirman** [nvdv/vprof#58]
Thanks for a great tool! This visual profiler is what I was looking for in Python.

I was surprised though that the code heatmap only shows the execution count for the colour highlighting, and for the mouseovers. For me it is far more interesting to know how long each line took, not just how many times it is run. Of course this is also somewhat in the flame graph, but not in the same format.

It would be great to be able to select what the code heatmap shows, effectively allowing the user to choose between the columns of [line_profiler](https://github.com/rkern/line_profiler). This could be in the command-line options, but ideally could be in a drop-down menu in the code heatmap screen. I believe matlab's profiler offers something similar.

Thanks

**Comment by nvdv** [comment]
Thanks for reporting!

**Comment by dlorch** [comment]
Upvote +1 for this feature request ;-)

**Comment by nvdv** [comment]
I've just pushed a few commits with initial version of this feature. Might be rough around the edges.
That's how code heatmap looked like:
![exec_heatmap](https://cloud.githubusercontent.com/assets/745431/23710288/4153e1d8-042d-11e7-8a04-2971e108dbb2.png)
That's how it looks now:
![time_heatmap](https://cloud.githubusercontent.com/assets/745431/23710303/4ebd7ec4-042d-11e7-9489-e821b449bd6f.png)

**Comment by dlorch** [comment]
This looks very cool!

**Comment by nvdv** [comment]
Thanks.
This feature still requires some improvements and more testing, so I will post updates here.

**Comment by nvdv** [comment]
I've just uploaded this feature to PyPI. At present It tracks main thread only, since it does not require major changes to UI.
