### ISSUE TITLE
Installation fails: node is not found

### ISSUE THREAD

**Issue by vladimir-low** [nvdv/vprof#6]
Installler couldn't install phantomjs dependency:

> phantomjs@1.9.19 install /home/vladimir/Sources/Python/vprof/node_modules/phantomjs
> node install.js

sh: 1: node: not found
npm http 304 https://registry.npmjs.org/align-text
npm http 304 https://registry.npmjs.org/align-text
npm http 304 https://registry.npmjs.org/lazy-cache
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 ...

# Possible solution:
Add nodejs-legacy as a requirement

**Comment by nvdv** [comment]
Looks like you're using outdated ```npm```. 
Install latest version of ```npm``` and it will work fine. I'll update the prerequisites.
