### ISSUE TITLE
Allow running external server

### ISSUE THREAD

**Issue by yaroslavvb** [nvdv/vprof#68]
It would be useful to have vprof launch server that listens for external connections. Similar to what jupyter allows. I'd like to launch it a devbox connected to firewalled LAN, so security is not an issue

**Comment by nvdv** [comment]
You can run `vprof` in remote mode (if that's what you need)
```sh
vprof -r 
```

```python
from vprof import runner

def foo(arg1, arg2):
    ...

runner.run(foo, 'cmhp', args=(arg1, arg2), host='localhost', port=8000)
```

**Comment by nvdv** [comment]
`vprof` is webapp, so you can set host name  and port  number of the server with `-H` and `-p`  flags respectively
```sh
vprof -c c example.py -H localhost -p 12345
```
