### ISSUE TITLE
Pass back return value from the profiled function

### ISSUE THREAD

**Issue by eudoxos** [nvdv/vprof#69]
`vprof.runner.run(...)` ignored return value of the function profiled. Would it be possible to pass it back?

(I would like to submit pull request but it actually is not as straightforward as I thought :/)

**Comment by nvdv** [comment]
Hi,
looks reasonable. I'll take a look 😄

**Comment by nvdv** [comment]
It's done.

**Comment by eudoxos** [comment]
Thanks!
