### ISSUE TITLE
Readme issue in installation step

### ISSUE THREAD

**Issue by vladimir-low** [nvdv/vprof#7]
README says:
"To install current dev version, clone this repository and execute
make install"

However it should be:
"sudo make install"

LOG:
Requirement already satisfied (use --upgrade to upgrade): psutil in /usr/lib/python2.7/dist-packages (from vprof==0.1.2)
Installing collected packages: vprof
  Running setup.py install for vprof
    Complete output from command /usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-Wd26mM-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), 
__file__, 'exec'))" install --record /tmp/pip-67vVFH-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/vprof
    copying vprof/__init__.py -> build/lib.linux-x86_64-2.7/vprof
    copying vprof/profile_wrappers.py -> build/lib.linux-x86_64-2.7/vprof
    copying vprof/__main__.py -> build/lib.linux-x86_64-2.7/vprof
    copying vprof/stats_server.py -> build/lib.linux-x86_64-2.7/vprof
    running egg_info
    creating vprof.egg-info
    writing requirements to vprof.egg-info/requires.txt
    writing vprof.egg-info/PKG-INFO
    writing top-level names to vprof.egg-info/top_level.txt
    writing dependency_links to vprof.egg-info/dependency_links.txt
    writing entry points to vprof.egg-info/entry_points.txt
    writing manifest file 'vprof.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'vprof.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'vprof.egg-info/SOURCES.txt'
    creating build/lib.linux-x86_64-2.7/vprof/frontend
    copying vprof/frontend/profile.html -> build/lib.linux-x86_64-2.7/vprof/frontend
    copying vprof/frontend/vprof.css -> build/lib.linux-x86_64-2.7/vprof/frontend
    copying vprof/frontend/vprof_min.js -> build/lib.linux-x86_64-2.7/vprof/frontend
    running install_lib
    creating /usr/local/lib/python2.7/dist-packages/vprof
    error: could not create '/usr/local/lib/python2.7/dist-packages/vprof': Permission denied
    
    ----------------------------------------
Command "/usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-Wd26mM-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" inst
all --record /tmp/pip-67vVFH-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-Wd26mM-build
make: *** [install] Error 1

**Comment by nvdv** [comment]
I would leave as it is, since it's not required on all systems and ```make install``` is supposed to be done by devs (who know what they do), not just regular users.
